# netlify.toml inside the frontend directory (used if Base directory is set to 'frontend')

[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
